version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - 6500:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - '/.env'
volumes:
  postgres_data:
